server: 
  port: 9066
  
spring: 
  application: 
    name: microservice-gateway-zuul
  
eureka:  
  client: 
    serviceUrl: 
      defaultZone: http://user:123@localhost:8761/eureka
  instance: 
    prefer-ip-address: true
  
zuul:
  routes:
    users:
      path: /myusers/**
      serviceId: MICROSERVICE-PROVIDER-USER
      
ribbon:
  eureka:
    enabled: false
      
MICROSERVICE-PROVIDER-USER:
  ribbon:
    listOfServers: localhost:8861,localhost:8862
    
zuul.PreZuulFilter.pre.disable: true
      
