server: 
  port: 9061

eureka:  
  client: 
    serviceUrl: 
      defaultZone: http://user:123@localhost:8761/eureka
  instance: 
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    
spring: 
  application: 
    name: microservice-consumer-movie-Ribbon
    
#clientname.ribbon.key: value