server: 
  port: 9065
  
security: 
  basic: 
    enabled: true
  user: 
    name: user
    password: 1

eureka:  
  client: 
    healthcheck:  
      enabled: true
    serviceUrl: 
      defaultZone: http://user:123@localhost:8761/eureka
  instance: 
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    
spring: 
  application: 
    name: microservice-consumer-movie-Ribbon-with-hystrix01
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000

//hystrix.shareSecurityContext: true